{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ationmc",
    "module": "AtionGradle",
    "version": "0.0.1-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AtionGradle-0.0.1-alpha.jar",
          "url": "AtionGradle-0.0.1-alpha.jar",
          "size": 44701,
          "sha512": "4a1a4c332dcca6749eeed20416bdc30b91f3033b99b3a7a3a17aae92a91f54c846af96cbfcb3e2e7d61ef24b4d300b6b3d547785888fd94fa92c465af88c2e41",
          "sha256": "4f24c45ce456e29e0f87ad91a8eedc7d2b11746ee8153576c189f6441f383c47",
          "sha1": "7a85a5519fd4140dad5d8082d7055e93b267e1ae",
          "md5": "44a16867a8d2a15c4349da033ee52da9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "AtionGradle-0.0.1-alpha.jar",
          "url": "AtionGradle-0.0.1-alpha.jar",
          "size": 44701,
          "sha512": "4a1a4c332dcca6749eeed20416bdc30b91f3033b99b3a7a3a17aae92a91f54c846af96cbfcb3e2e7d61ef24b4d300b6b3d547785888fd94fa92c465af88c2e41",
          "sha256": "4f24c45ce456e29e0f87ad91a8eedc7d2b11746ee8153576c189f6441f383c47",
          "sha1": "7a85a5519fd4140dad5d8082d7055e93b267e1ae",
          "md5": "44a16867a8d2a15c4349da033ee52da9"
        }
      ]
    }
  ]
}
