{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ationmc",
    "module": "AtionGradle",
    "version": "0.0.1-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AtionGradle-0.0.1-alpha.jar",
          "url": "AtionGradle-0.0.1-alpha.jar",
          "size": 44694,
          "sha512": "75289bd61e7fab7c4af64d20e6e8004a1f29024a891a4179a60eea3e004efe78124953eb3a65e5f9c7db57faf98a590fc34550c0cd1d55f44a04f7abe56eed4e",
          "sha256": "c36299921707974b523c4a683b20bb95d637f1da47b21495186828977d3d163b",
          "sha1": "d0c94b5a0f7d1ef6a048c051c4dc76378460f754",
          "md5": "fa04e337b39041d9896e4605ea17406f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "AtionGradle-0.0.1-alpha.jar",
          "url": "AtionGradle-0.0.1-alpha.jar",
          "size": 44694,
          "sha512": "75289bd61e7fab7c4af64d20e6e8004a1f29024a891a4179a60eea3e004efe78124953eb3a65e5f9c7db57faf98a590fc34550c0cd1d55f44a04f7abe56eed4e",
          "sha256": "c36299921707974b523c4a683b20bb95d637f1da47b21495186828977d3d163b",
          "sha1": "d0c94b5a0f7d1ef6a048c051c4dc76378460f754",
          "md5": "fa04e337b39041d9896e4605ea17406f"
        }
      ]
    }
  ]
}
